import type { Metadata } from "next";
import { Inter, Moulpali } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { h2 } from "motion/react-client";
import LaodingCard from "@/components/LoadingCard";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const moulpali = Moulpali({
  weight: '400',
  variable: "--font-moulpali",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${moulpali.variable} antialiased`}
      >
        <Suspense fallback={<LaodingCard/>
        }>
        {children}
        </Suspense>
      </body>
    </html>
  );
}
